language: python
dist: xenial
os: linux
python:
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install -U pip
  - pip install -U -e .[test,qa] wheel python-coveralls coverage
  - pip install dataclasses; python_version == '3.6'
script:
  - pytest --cov drafts
  - flake8 drafts
  - python setup.py bdist_wheel
after_success:
  - coveralls
